name: Project linting workflow

on: [push, pull_request]

jobs:
  complete-linting:
    runs-on: ubuntu-latest
    name: Complete linting
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install tools
        run: |
          pip install "black==v21.11b0" \
          "flake8>=3.7.9, <=4.0.1" \
          "isort>=4.3.21, <=5.10.1" \
          "mypy~=0.902" \
          "pydocstyle~=6.1.1" \
          "types-requests~=0.1.9" \

      - name: Run Black
        run: black src/
        working-directory: ${{env.working-directory}}

      - name: Run flake8
        run: flake8 src/
        working-directory: ${{env.working-directory}}

      - name: Run isort
        run: isort -rc src/
        working-directory: ${{env.working-directory}}

      - name: Run pydocstyle
        run: pydocstyle src/
        working-directory: ${{env.working-directory}}

      - name: Run mypy
        run: mypy src/
        working-directory: ${{env.working-directory}}